### PR TITLE
Http proxy

### LINKED ISSUE #189: Explain how to set HTTP proxy for the "dita" command
For example the topics may have image references to remote HTTP images and the user who runs the process is behind a proxy web server.
Usually when a Java process starts you give it the proxy details as command line arguments, for example like:

                "jre1.8.0_152-x64/bin/java" "-Dhttp.proxySet=true" "-Dhttp.proxyHost=myproxy.com" "-Dhttps.proxyHost=myproxy.com" "-Dhttp.proxyPort=8080" "-Dhttps.proxyPort=8080" ...............

From what I looked into the "dita.bat":

           "%_JAVACMD%" %ANT_OPTS% -Djava.awt.headless=true .....................

the only way to properly pass the HTTP proxy system properties is to define the ANT_OPTS as an environmental variable having as value:

            "-Dhttp.proxySet=true" "-Dhttp.proxyHost=myproxy.com" "-Dhttps.proxyHost=myproxy.com" "-Dhttp.proxyPort=8080" "-Dhttps.proxyPort=8080"

@jelovirt Is there a better way to pass such Java system properties to the process?
Somehow I would have expected that "-Dname=value" properties passed to the "dita" process would also be set by the "org.dita.dost.invoker.Main" as Java system properties but you only set them as ANT project parameters.

### PR DESCRIPTION
**Pull request by EditKoselak**
## Description
Explain how to set HTTP proxy for the "dita" command

## Motivation and Context
Fixes #189

## How Has This Been Tested?
The documentation was compiled locally using the `gradlew -PditaHome=/path/to/dita-ot` command

## Type of Changes
Documentation

## Documentation and Compatibility
No additional documentation needed.

## Checklist

- My code follows the code style of this project.
    -  <https://github.com/dita-ot/dita-ot/wiki/Java-Coding-Conventions> - N/A
    -  <https://github.com/dita-ot/dita-ot/wiki/XSLT-Coding-Conventions> - N/A
    -  <https://github.com/dita-ot/docs/wiki/coding-guidelines> - checked
- I have updated the unit tests to reflect the changes in my code. - N/A

### CODE REVIEW

**Review by infotexture — CHANGES_REQUESTED** [review]
The long line in this code block will require horizontal scrolling in HTML output, and be truncated in PDF output.

We may want to consider inserting `\` line continuation characters in the code block to ensure the example remains readable, but I'm not sure if those can be encoded within the `ANT_OPTS` value in a way that works on all platforms. (Perhaps @raducoravu knows?) 🤔

**Comment by infotexture** [comment]
I'm also thinking we might want to move this information to a dedicated topic, perhaps in the [Troubleshooting](https://www.dita-ot.org/dev/topics/troubleshooting-overview) section, where other `ANT_OPTS` workarounds are described, but I can do that in a separate step.

**Comment by EditKoselak** [comment]
> The long line in this code block will require horizontal scrolling in HTML output, and be truncated in PDF output.
> 
> We may want to consider inserting `\` line continuation characters in the code block to ensure the example remains readable, but I'm not sure if those can be encoded within the `ANT_OPTS` value in a way that works on all platforms. (Perhaps @raducoravu knows?) 🤔

Thank you for the suggestions! We tested the "\" solution in bask and sh and it worked. We hope that this is OK on other platforms. Let us know if any further correction is needed.

**Review by raducoravu — CHANGES_REQUESTED** [review]
Maybe instead of "for installing and downloading content" I would say "for installing plugins from the configured registry or processing remote referenced resources"

This part "provide the proxy configuration via the ANT_OPTS environment variable", on various operating systems there are various ways to set env variables, on Windows I would use in a Command Prompt window "set envName=envValue" and then I would call "dita..." on a separate line. On Mac OS I would use in the Terminal "export envName=envValue". I think this would be the same for Linux.
Also the "dita install <plug-in>" part should probably be on a separate line in the codeblock.

**Comment by EditKoselak** [comment]
Hello @infotexture, @raducoravu,
thanks for the suggestions. Since adding extra info would make the note pretty complex, I think it would be better to move it to a separate section under Troubleshooting/[Other error messages](https://www.dita-ot.org/dev/topics/other-errors) (Connection timed out), and create something similar to what we have in [Increasing Java memory allocation](https://www.dita-ot.org/dev/topics/increasing-the-jvm). 
We could keep a reference as a Tip in the original chapter ([Arguments and options for the dita command](https://www.dita-ot.org/dev/parameters/dita-command-arguments)).
What do you think?

**Comment by infotexture** [comment]
@EditKoselak Yes, I think that's the right approach.

**Review by infotexture — APPROVED** [review]
🙇 Thanks for your input here, looks pretty good now.

I implemented the feedback from @raducoravu in https://github.com/dita-ot/docs/pull/501#pullrequestreview-1673694513 and prepared a few tweaks, but I'm not able to push additional commits to your fork as part of this PR, so I'll merge this as is now, and submit those separately.

**Pull request merged**
