### PR TITLE
Adding an example

### PR DESCRIPTION
**Pull request by xephon2**
The example shows how to use the same strings in various languages.

## Description
Added an example showing how to add strings to multiple languages.

## How Has This Been Tested?
Tested on my local machine.

## Type of Changes
Docs improvement

## Checklist

- My code follows the code style of this project.
    -  <https://github.com/dita-ot/dita-ot/wiki/Java-Coding-Conventions>
    -  <https://github.com/dita-ot/dita-ot/wiki/XSLT-Coding-Conventions>
    -  <https://github.com/dita-ot/docs/wiki/coding-guidelines>
- I have updated the unit tests to reflect the changes in my code.

### CODE REVIEW

**Comment by infotexture** [comment]
@xephon2 Thanks for submitting this. 🙏 You need to [sign your work](http://www.dita-ot.org/DCO) to give us permission to use  your contribution.

To sign off your last commit, use:

```
git commit --amend --signoff
```

Then force-push to update the branch on your fork with:

```
git push --force-with-lease
```

**Comment by xephon2** [comment]
@infotexture, not sure why Prettier fails.

**Comment by infotexture** [comment]
@xephon2 No worries, I'll run it locally and push another commit to clean that up before merging.

**Comment by infotexture** [comment]
Stripped unnecessary generated IDs per [coding guidelines](https://github.com/dita-ot/docs/wiki/coding-guidelines#avoid-unnecessary-markup) & re-ran Prettier to fix the failing check.

- The IDs should not be generated if you edit the files from the oXygen project, which contains settings to prevent this. 
- Prettier should run automatically if you follow the [setup steps](https://github.com/dita-ot/docs#installing-formatting-tools) in the ReadMe.

**Comment by xephon2** [comment]
Just for explanation what I did: I clicked the "edit this page" button and implemented the change in the oxygen web author. It crashed when trying to commit. Then I switched to the XML view and copied the snippet to the clipboard and added it via the GitHub online editor. I'm not permitted to submit normal PRs to public repositories on my business laptop. This is blocked by the IT policy.

**Comment by jelovirt** [comment]
You can also use GitHub's CodeSpaces. Just press `.` (dot) on your browser when you're on your fork of the docs repo and VS Code will open in your browser. You can create a PR branch there, make your changes, commit them, and open a PR.

**Comment by jelovirt** [comment]
Though, IIRC you can't install Prettier on the browser VS Code, so you still have to run Prettier somewhere.

**Comment by infotexture** [comment]
Yes, this is an unfortunate limitation of browser-based editing workflows. 

Most don't support/enforce project conventions like signoff and linting.

**Pull request merged**
