### PR TITLE
Add samples files from the OT repo

### PR DESCRIPTION
**Pull request by shaneataylor**
To facilitate using the samples files for examples in the documentation, moving these files out of the dita-ot repo and into the docs repo.

### CODE REVIEW

**Comment by jelovirt** [comment]
@infotexture @robander this is your call, I have no strong feelings about samples, other than they should not be a submodule (due to added management complexity).

**Comment by infotexture** [comment]
:+1: I'm inclined to merge this, as I think it makes sense to treat samples as part of the documentation _(which references them)_ rather than as core OT code.

Per discussion in dita-ot/dita-ot#2205, this would make it easier for the docs team to maintain samples, generate new sample content and reference samples via `<coderef>`.

**Comment by infotexture** [comment]
@shaneataylor: This changes the path to `samples` in distribution packages to `docsrc/samples`.

Would you be able to extend this PR with a new commit that updates [creating-an-ant-build-script.dita](https://github.com/dita-ot/docs/blob/develop/user-guide/creating-an-ant-build-script.dita) and [using-dita-command.dita](https://github.com/dita-ot/docs/blob/develop/user-guide/using-dita-command.dita) accordingly?

**Comment by shaneataylor** [comment]
@infotexture: Will do.

@jelovirt, @infotexture: What do you think about either updating the docs build to copy `docsrc/samples` to its accustomed location for increased findability, or making a `samples` symlink to `docsrs/samples` in the distros (although I'm not sure how to do this for Windows)?

**Comment by infotexture** [comment]
@shaneataylor: Thanks.

Not sure we really need to copy the content to its old location, as the `docsrc/samples` folder will be included in the distribution packages, plus any topics referenced there from the root map in `docs` would also appear in the output folder `doc/samples`.

Not sure how many people discover samples by peeking into distribution subfolders, but I think as long as the docs refer to the new location, we should be fine.

**Comment by shaneataylor** [comment]
@infotexture I updated the topics and I'm fine with the move from `samples` to `docsrc/samples`.

**Pull request merged**
