### PR TITLE
🚧 Draft 4.0.2 docs

### PR DESCRIPTION
**Pull request by infotexture**
## Generate release branch preview for 4.0.2 docs

This pull request generates a deploy preview for the release branch to facilitate reviews.

- It will **not** be merged via the GitHub UI. 
- The branch will be merged automatically when the release is tagged via Git Flow and the merge commit is pushed.

### CODE REVIEW

**Comment by chrispy-snps** [comment]
@infotexture - for the `--resource` fix, I have a slight preference for this wording:

> ... , the resource map was overwritten with its temporary version from preprocessing.

Everything else looks great. Thanks!

**Comment by raducoravu** [comment]
Read the build notes, again about the --resource fix, some suggestions about the original description:

         When an auxiliary map resource was passed to the dita command with the --resource option or the args.resources parameter, the resource map was replaced with a temporary version. 
         These maps are now copied instead of overwritten in-place, and the key values they contain are correctly resolved from the copies in the temporary folder.

Maybe I would replace:

When an auxiliary map resource->When a context map resource
because it's usually given as a keys context, to resolve keyrefs in the topic.

the resource map was replaced with a temporary version-> this did not occur in all cases, the folder hierarchy for this to happen would have needed to look like this:

    mapFolder/
                   map.ditamap
                   topics/
                             topic.dita
                             ditaot-tempFolder/
so maybe modify a bit the description to state that in certain cases this may have occurred.

These maps are now copied instead of overwritten in-place->These maps are now correctly copied and processed to the temporary files folder instead of their contents being replaced...

**Comment by chrispy-snps** [comment]
@raducoravu - is the required condition simply that the context map is outside the directory scope containing the input topic file?

**Comment by raducoravu** [comment]
@chrispy-snps from what I remember I tested with the map and topic in the same folder and in this case I do not think the problem could be reproduced. I tested with the map in the folder above the topic and the problem could be reproduced. I do not think I tested another configuration.

**Pull request merged**
