### PR TITLE
Initial draft of PDF2 change bar creation topic

### PR DESCRIPTION
**Pull request by drmacro**
Here's my initial stab at documenting the change bar creation details for PDF2.

### CODE REVIEW

**Comment by infotexture** [comment]
Looks good, thanks.

I'd probably move the new keys to the master key map `keyrefs.ditamap` so they're all in one place.

**Comment by infotexture** [comment]
**Markup question:** When referencing keys, is there a reason to re-specify the `@format` & `@scope` attributes that are already included in the key definition?

It seems easier to condense the reference like `<xref keyref="fo-spec.change-bar-start"/>` assuming the link text is stored in the key like this:

```xml
<keydef keys="fo-spec.change-bar-start"
    scope="external"
    format="html"
    href="http://www.w3.org/TR/xsl/#fo_change-bar-begin">
  <topicmeta>
    <linktext>XSL-FO fo:change-bar-begin element</linktext>
  </topicmeta>
</keydef>
```

I suppose there are cases where you might want to override the link text in a particular reference, but since these are only used once at the moment, it seems sensible to put everything in the key definition.

Just curious…

**Comment by keberlein** [comment]
I would put the necessary @format and @scope in the key definition
    and NOT the key reference.
    
    Putting the attributes on the key reference can have unfortunate
    (and usually unintended) consequences when it acts as an override.
    
    Best,
      Kris
      
      Kristen James Eberlein
      Chair, OASIS DITA Technical Committee
      Principal consultant, Eberlein Consulting
      www.eberleinconsulting.com
      +1 919 682-2290; kriseberlein (skype)
      
    
    On 7/29/2015 8:20 AM, Roger Sheen
      wrote:
    
    
      Markup question: When referencing keys, is
        there a reason to re-specify the @format & @scope
        attributes that are already included in the key definition?
      It seems easier to condense the reference like <xref
          keyref="fo-spec.change-bar-start"/> assuming the
        link text is stored in the key like this:
      
        <keydef keys="fo-spec.change-bar-start"
    scope="external"
    format="html"
    href="http://www.w3.org/TR/xsl/#fo_change-bar-begin">
  <topicmeta>
    <linktext>XSL-FO fo:change-bar-begin element</linktext>
  </topicmeta>
</keydef>
      
      I suppose there are cases where you might want to override the
        link text in a particular reference, but since these are only
        used once at the moment, it seems sensible to put everything in
        the key definition.
      Just curious…
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by robander** [comment]
I think putting the link text inline can go either way - plus side, you know how the content is going to read, down side that you can't change it with the key definition. But I would definitely keep `@scope` and `@format` only on the key definition, so that the href/scope/format values all stay together and (if needed) change together.

**Comment by drmacro** [comment]
Yes, the @format and @scope should only be on the keydef. If they were on the xref that's my oversight and a side effect of how oXygen creates links--the current version's UI for creating key-based links is not ideal.

**Comment by infotexture** [comment]
OK. Would you like to push additional commits to the feature branch before I merge, or shall I make the changes after merging?

(See my [comments](https://github.com/drmacro/docs/commit/39ee5e2bfde20c012647834fdeae8fb22853d520#commitcomment-12418263) above re. `fo:change-bar-begin`, etc.)

**Comment by infotexture** [comment]
Will do.

**Comment by infotexture** [comment]
New topic available in dev docs: http://www.dita-ot.org/dev/user-guide/pdf2-creating-change-bars.html.

**Pull request merged**
