### PR TITLE
Suggestion on extension point docs.

### PR DESCRIPTION
**Pull request by markgif**
Signed-off-by: Mark Giffin <m1879@earthlink.net>

## Description
I have run into baffling things when using extensions points. I realized that using an extension point in my custom plugin can cause that extension point action to also run when other unrelated plugins are run.

## Motivation and Context
This info could help if it were in the docs.

## How Has This Been Tested?
No code changes. I changed one DITA topic by adding a draft-comment and validated it in Oxygen.

## Type of Changes
no code - suggestion

## Documentation and Compatibility
This is a documentation suggestion.

## Checklist
- My code follows the code style of this project.
- no code

### CODE REVIEW

**Comment by markgif** [comment]
Looks like it failed on pretty printing. I went back and carefully tried to match the existing pretty printing, but I don;t know how to update the topic in this PR>

**Comment by infotexture** [comment]
@markgif Thanks for the suggestion. 🙏 

The failing Prettier check is easy enough to fix, but we can ignore that for now, as we won't merge this as is. 
For future reference, the README includes instructions on [Installing formatting tools](https://github.com/dita-ot/docs#installing-formatting-tools) and [Running Prettier](https://github.com/dita-ot/docs/pull/452).

Regarding the [problem you mentioned](https://github.com/dita-ot/docs/pull/452/files#diff-bd73e4f236297f57b84b6a8f858038faea97a7732d744f8a99fd1b26e41c5c32R17-R23) with **oXygen XML Web Author** not offering to fork the repo, @raducoravu suggested in a related https://github.com/dita-ot/docs/issues/443#issuecomment-1344089885 a while back that oXygen may have difficulty recognizing your fork if it was created long ago.

> I have run into baffling things when using extensions points. I realized that using an extension point in my custom plugin can cause that extension point action to also run when other unrelated plugins are run.

Your [suggestion](https://github.com/dita-ot/docs/pull/452/files#diff-bd73e4f236297f57b84b6a8f858038faea97a7732d744f8a99fd1b26e41c5c32R13-R16) to add info on  conditionalizing extension point actions is welcome, but I think we'd need to provide a few examples to illustrate the recommended approach.

Perhaps @robander or @jelovirt have ideas on best practices for isolating extension point actions so they only run when using the plug-in they come with.

**Comment by markgif** [comment]
Hi Roger! I am coming up with a couple examples of how an extension point can be isolated, more soon.

**Comment by markgif** [comment]
Hi @infotexture - Here are my examples of how to limit the effect of using certain extension points in a custom plugin.

### Example 1.

My custom plugin with a custom transtype (my.transtype) overrides the html5 transtype by using an extension point to run a custom Java class. It works fine with the custom transtype, but it also runs with the default html5 transtype, and with html5-based Oxygen Webhelp, which are unwanted.

plugin.xml has this preprocess extension point added:

```
<feature extension="depend.preprocess.chunk.pre" value="remove-chunk"/>
<!-- add the Java class to the classpath -->
<feature extension="dita.conductor.lib.import" file="java/RemoveChunk.jar"/>
```
integrator.xml has this target named after the value of the extension point. It runs the Java class:

```
<target name="remove-chunk">
  <loadfile property="inputfile" srcfile="${dita.temp.dir}/usr.input.file.list"/>
  <echo>Removing chunk attributes from map: ${dita.temp.dir}/${inputfile}</echo>
  <java classname="RemoveChunk">
    <arg value="${dita.temp.dir}/${inputfile}"/>
  </java>
</target>
```

But this makes the Java class run with every html5-based output (at least), even though it is contained in a standard plugin, and we don't want that. See below for the fix for this problem.

integrator.xml:

```
<!-- add a condition that checks the transtype -->
<condition property="isMyTranstype">
  <matches pattern="my.transtype" string="${transtype}"/>
</condition>
```
```
<!-- check the condition before running the remove-chunk target -->
<target name="remove-chunk" if="${isMyTranstype}">
  ...
</target>
```

See the next comment for Example 2.

**Comment by markgif** [comment]
### Example 2.

This custom plugin overrides the xhtml transtype.

plugin.xml:

```
<!-- run Python script at this extension point -->
<feature extension="depend.preprocess.post" value="my.script"/>
```

integrator.xml:

```
<!-- add condition so it runs only when the transtype is xhtml or my.transtype -->
<condition property="run.script">
  <or>
    <equals arg1="${transtype}" arg2="xhtml"/>
    <equals arg1="${transtype}" arg2="my.transtype"/>      
  </or>
</condition>
```

```
<!-- check the condition before running this target -->
<target name="run.python.script" if="${run.script}">
  ...
</target>
```

**Comment by infotexture** [comment]
@markgif Thanks for your suggestions here. Implemented in https://github.com/dita-ot/docs/commit/8e9160cf1bf8e573c0b1a9d1ecddf961d1d7074e.

**Pull request closed without merging**
