### PR TITLE
121 New TOC organization

### PR DESCRIPTION
**Pull request by shaneataylor**
@infotexture Although there's more work to be done generally with the docs, I think this reorganization represents an MVP set of changes that moves us forward.

### CODE REVIEW

**Comment by infotexture** [comment]
👍 At first glance, this looks like a step in the right direction.

I'll pull the changes to build & test locally, then push to a staging server for further review.

In the meantime, are you able to update the feature branch and amend your commit with a signoff line per http://www.dita-ot.org/DCO ?

It's OK to force-push to your fork in this case: `git push --force-with-lease yourfork`.

**Comment by shaneataylor** [comment]
@infotexture Signed off. Thanks for reviewing & testing.

**Comment by infotexture** [comment]
@shaneataylor 🙇 Thanks, this looks like a much better overall structure that should help users to find what they're looking for more quickly.

There are still a few rough edges, but I think this will serve as a solid basis for further refinements. _Detailed comments to follow…_

**Comment by infotexture** [comment]
Several duplicate topics erroneously appear as children of the [landing page](http://infotexture.github.io/dita-ot.github.io/preview).

Not sure if that's intentional.

**Comment by infotexture** [comment]
IMHO 👎 for the _Release Notes_ archive, we have the **Documentation** versions menu for that.

Would also fill the PDF with extra pages and noise.

I've long considered removing the old _Release Notes_ topics from the repo entirely, as they can be accessed via Git tags if they're ever needed.

— but I realize I may hold a minority position on this topic, so open for other opinions.

**Comment by xephon2** [comment]
- I'd suggest to merge **Prerequisite software** with **Installing the DITA Open Toolkit**. Currently it's a child, that does not make sense.
- I'd suggest to create a new concept topic called **Plugins**, explain there what a plugin is and then move **Installing plug-ins** and **Removing plug-ins** as child nodes to that topic.

**Comment by infotexture** [comment]
"Next topic" links still reflect old hierarchy, but many such things may be coming from reltables and submaps that have not yet been updated, so this is to be expected.

**Comment by infotexture** [comment]
[Building output](http://infotexture.github.io/dita-ot.github.io/preview/user-guide/transforming-dita-content.html) has too many children. Parameters is better nested under Reference, and the output formats under [DITA-OT transformations](http://infotexture.github.io/dita-ot.github.io/preview/user-guide/AvailableTransforms.html) _(though they appear there when viewing the page directly, so this may just be another map hierarchy glitch)_.

**Comment by robander** [comment]
>>> IMHO 👎 for the Release Notes archive, we have the Documentation versions menu for that.
Would also fill the PDF with extra pages and noise.
I've long considered removing the old Release Notes topics from the repo entirely, as they can be accessed via Git tags if they're ever needed.
— but I realize I may hold a minority position on this topic, so open for other opinions.

I think I agree on not having the old versions, and definitely not having them in PDF. It's easy to find by switching versions on the landing page. I'm inclined to keep them in the repo because it means we still have them in the distribution, so people can find them -- I've used that before to more easily figure out when something shipped. Not sure if others have had that need, but I think it's fair to say a large number of DITA-OT users would not know to go look for Git tags if they wanted that info.

**Comment by infotexture** [comment]
Under [Customizing HTML output](http://infotexture.github.io/dita-ot.github.io/preview/dev_ref/html-customization.html):

* [Customizing HTML with a .properties file](http://infotexture.github.io/dita-ot.github.io/preview/dev_ref/html-customization-properties-file.html) appears twice
* :+1: for promoting [Handling content outside the map directory](http://infotexture.github.io/dita-ot.github.io/preview/parameters/generate-copy-outer.html)
* Children of [Setting parameters for custom HTML](http://infotexture.github.io/dita-ot.github.io/preview/dev_ref/html-customization-parameters.html) appear un-nested, alongside parent.

**Comment by xephon2** [comment]
@robander, I'd suggest to keep the old PDF notes in a static place and simply add them with

```xml
<topicref href="DITA-OT-1.8.5-ReleaseNotes.pdf" format="html" scope="external">
  <navtitle>1.8.x</navtitle>
  <shortdesc>DITA-OT 1.8.x Release Notes</shortdesc>
</topicref> 
```

So the user can access all notes the same way and does not have to care for their format.

**Comment by infotexture** [comment]
Under [Customizing PDF output](http://infotexture.github.io/dita-ot.github.io/preview/dev_ref/pdf-customization.html):
- Good idea to promote [Generating revision bars](http://infotexture.github.io/dita-ot.github.io/preview/user-guide/pdf2-creating-change-bars.html) — strictly speaking this does not require any toolkit customizations — just markup changes, but that distinction is likely irrelevant to users, so :+1:
- The value of the [History of the PDF transformation](http://infotexture.github.io/dita-ot.github.io/preview/dev_ref/pdf-transformation-history.html) topic is debatable, per #167

**Comment by infotexture** [comment]
:+1: for promoting [Customizing generated text](http://infotexture.github.io/dita-ot.github.io/preview/dev_ref/plugin-addgeneratedtext.html).

For related issues, see #31 & #165.

**Comment by infotexture** [comment]
@robander:

> I did really like having Parameters at top level of TOC when it moved up back in 2.1

I recall similar feedback from @jelovirt, so this may be worth considering. I think the focus for the reorganization has been on the needs of first-time users and making things more approachable, but we shouldn't lose sight of veterans' needs entirely.

**Comment by infotexture** [comment]
[Other customizations](http://infotexture.github.io/dita-ot.github.io/preview/dev_ref/plugin-creating.html) needs a bit more grouping, but the old [Creating plug-ins](http://www.dita-ot.org/dev/dev_ref/plugin-creating.html) topic was also a bit … _diverse_, so this is no surprise. 

The old plugin overview topics are un-nested, & [Customizing generated text](http://infotexture.github.io/dita-ot.github.io/preview/dev_ref/plugin-addgeneratedtext.html) was promoted, so shouldn't be here.

**Comment by infotexture** [comment]
Not sure about [Verifying output](http://infotexture.github.io/dita-ot.github.io/preview/verifying-output.html) as a top-level section w/ just one "Log files" child, but if there's more to come it may make sense.

I'd be fine leaving the "Log files" topic in Troubleshooting for now, and promote it later as suitable siblings emerge.

**Comment by infotexture** [comment]
So, that concludes my initial brain dump of feedback. Hoping others will chime in too.

For quick straw polls, adding 👍 / 👎 reactions to existing comments makes it easy to tally consensus.

**Comment by infotexture** [comment]
See #166 for additional thoughts on the re-organization of plugin-related content.

**Pull request merged**
