### PR TITLE
Generate parameter reference from plugin files

### PR DESCRIPTION
**Pull request by jelovirt**
Parameter reference topics for each transtype are generated during integration and additional details are populated with push conref.

### CODE REVIEW

**Comment by jelovirt** [comment]
@infotexture could you do a review? This implementation more or less reproduces the current output, with some of the titles differing. We could add a push conref to titles if we want to update those?

**Comment by infotexture** [comment]
Looks pretty good. Added autogenerated results to `.gitignore` in infotexture/docs@297fff3a9cf023833977c95c89a9fc31e96175eb.

One file appears to be missing after generation: `ant-parameters-pdf2-transformation.dita`. It's apparently generated as `ant-parameters-pdf-transformation.dita` along with the others, but apparently linked as `...pdf2...`

Would be good if we could tweak the titles. First title for `ant-parameters-base-transformation.dita` has trailing colon, HTMLHelp needs a space, etc.

**Comment by infotexture** [comment]
Fixed link to PDF parameters in infotexture/docs@98b16493966de0b42406f89e2046571968265008.

This topic needs a `<shortdesc>`.

**Comment by jelovirt** [comment]
Verify that you have the latest `dita-ot/dita-ot` commit when you run the integrator, the `pdf` vs. `pdf2` should be changed there. Thus 98b16493966de0b42406f89e2046571968265008 fixes this in the wrong place. Unless, of course, we want to call the trastype "pdf" and not "pdf2". The name "pdf2" is a name that makes sense only if you've been with OT since the days of "legacy-pdf".

**Pull request merged**
