### PR TITLE
Store API documentation

### PR DESCRIPTION
**Pull request by jelovirt**
# Background

Originally DITA-OT assumed all input and output resources were on local disk and addressable with a file path. At some point, support for URI input was added, so e.g. HTTPS resources could be used as input. Both temporary and output resources were still file based.

# Store API

The Store API (`org.dita.dost.store.Store`) is an Java abstraction over temporary file operations. So for example instead of reading resources directly with`FileInputStream`, the Store API provides operations for this. This abstraction allows implementations of the Store API to choose how they handle resources, enables optimizations or non-file based storage. Since DITA-OT processes a lot of XML data, the Store API offers operations for XML processing directly. For example, a read method to directly get a DOM `Document`, instead of opening a file stream manually, parsing it with an XML parser, and getting the `Document` instance from the parser.

The Store API is extendable using Java's [Resource Loader](https://docs.oracle.com/javase/9/docs/api/java/util/ServiceLoader.html) with service `org.dita.dost.store.StoreBuilder`. This is a builder interface to get named `Store` instances ("a Store")

## Stream Store

This Store could also be File Store, since it uses disk and local files for temporary resources. This is the traditional DITA-OT implementation, where temporary XML files are store under `dita.temp.dir` path.

The Stream Store can be activated with property `store-type=file`.

The Stream Store was added in DITA-OT 3.5.

## Cache Store

This Store is an in-memory Store, that keeps all temporary resources in memory. The name comes from the feature of the Store, that it caches the parsed XML after reading. That is, instead of storing XML as a byte array, it keeps it as a DOM `Document` or S9api `XdmNode`. When the same resource is read again, it doesn't have to parse it again, only return the parsed document. Resources that are no under the temporary directory, are handled with the Stream Store.

Note that while the Store doesn't write anything to the temporary directory, it will still use URIs where the resources are under the temporary directory. The URIs are simply used for addressing, similary to URNs. Future releases of DITA-OT may use some other method of addressing, such as `tmp` URI scheme.

The Stream Store can be activated with property `store-type=memory`.

Preview of the Cache Store was added in DITA-OT 3.6. Not all custom plug-ins work with the Store, because they may assume files are used and use direct file access for resource operations.

### CODE REVIEW

**Comment by infotexture** [comment]
> The Stream Store can be activated with property `store-type=file`.
> The Stream Store was added in DITA-OT 3.5.

@jelovirt I don't see any references to that in the [3.5 _Release Notes_](https://www.dita-ot.org/3.5/release-notes/). Looks like these changes were added with https://github.com/dita-ot/dita-ot/pull/3548, which landed on `develop` August 7, between 3.5.2 & 3.5.3, but are not yet present in a 3.5.x release. 
— Have I misunderstood?

As for “can be activated with property `store-type=file`” it seems that's already the default, so not something users would need to do unless they had switched to `memory`, right?

**Comment by infotexture** [comment]
> Not all custom plug-ins work with the Store, because they may assume files are used and use direct file access for resource operations.

@jelovirt To take advantage of the Store, is it sufficient to use the custom `<pipeline>` elements as described in [Plug-in coding conventions](https://www.dita-ot.org/dev/topics/plugin-coding-conventions.html) ?

**Comment by infotexture** [comment]
@jelovirt Can we summarize the main benefit of in-memory store from the users' perspective? Is it primarily about processing speed?

**Comment by jelovirt** [comment]
> I don't see any references to that in the 3.5 Release Notes. Looks like these changes were added with dita-ot/dita-ot#3548, which landed on develop August 7, between 3.5.2 & 3.5.3, but are not yet present in a 3.5.x release.

Quote right. It was not shipped in 3.5, it was is part of 3.6.

>As for “can be activated with property store-type=file” it seems that's already the default, so not something users would need to do unless they had switched to memory, right?

Yes.

> To take advantage of the Store, is it sufficient to use the custom <pipeline> elements as described in Plug-in coding conventions ?

Yes. You can't use it with the Ant `<xslt>` task, you need `<pipeline><xslt>`.

>  Can we summarize the main benefit of in-memory store from the users' perspective? Is it primarily about processing speed?

Speed is one where we possibly will get more performance. There may also be cases where users prefer to use memory instead of disk for some reason, like some cloud computing platforms. This is a preview feature and we're trying to see what sort of benefits it may give.

**Pull request merged**
